import logging
import os
import time
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

STATIC_EXPORTS_DIR = os.path.join("static", "exports")


def ensure_exports_directory():
    """Ensures the static/exports directory exists."""
    os.makedirs(STATIC_EXPORTS_DIR, exist_ok=True)


def _clean_text(text: str) -> str:
    """Replaces non-ASCII or problematic characters for standard FPDF latin-1 fonts."""
    if not text:
        return ""
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2026": "...",
        "\u00a0": " ",
        "’": "'",
        "“": '"',
        "”": '"',
        "–": "-",
        "—": "-",
        "…": "..."
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def save_pdf(
    layout: List[Dict[str, Any]],
    story_title: str = "ComicCraft AI Chronicle",
    character_name: str = "Hero",
    tone: str = "Dramatic",
    art_style: str = "Comic Book Classic"
) -> str:
    """
    Compiles the comic layout into a multi-page PDF using FPDF/fpdf2.
    Saves the file to static/exports/comic_{timestamp}.pdf and returns the relative URL.
    """
    ensure_exports_directory()

    try:
        from fpdf import FPDF
    except ImportError:
        logger.error("FPDF is not installed. Please install fpdf2 via pip.")
        raise RuntimeError("PDF generation requires fpdf2 or fpdf library.")

    timestamp = int(time.time())
    safe_title = "".join(c for c in story_title[:24] if c.isalnum() or c in (" ", "_", "-")).strip().replace(" ", "_")
    filename = f"comic_{safe_title}_{timestamp}.pdf"
    output_path = os.path.join(STATIC_EXPORTS_DIR, filename)

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)

    # ----------------------------------------------------
    # COVER PAGE
    # ----------------------------------------------------
    pdf.add_page()
    # Dark Cover Background
    pdf.set_fill_color(15, 23, 42) # Slate 900
    pdf.rect(0, 0, 210, 297, "F")

    # Cover Border
    pdf.set_draw_color(255, 87, 34) # Vibrant Comic Punch
    pdf.set_line_width(2.0)
    pdf.rect(10, 10, 190, 277)
    pdf.set_draw_color(248, 250, 252)
    pdf.set_line_width(0.8)
    pdf.rect(13, 13, 184, 271)

    # Header Badge
    pdf.set_xy(20, 25)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(255, 87, 34)
    pdf.cell(170, 8, _clean_text("COMICCRAFT AI STUDIOS // SPECIAL EDITION"), align="C", new_x="LMARGIN", new_y="NEXT")

    # Title
    pdf.ln(18)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(255, 255, 255)
    clean_title = _clean_text(story_title).upper()
    pdf.multi_cell(170, 12, clean_title, align="C")

    # Subtitle / Hero
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 14)
    pdf.set_text_color(203, 213, 225)
    pdf.cell(170, 8, _clean_text(f"Featuring: {character_name}"), align="C", new_x="LMARGIN", new_y="NEXT")

    # First panel preview if available on cover
    first_panel_img = None
    if layout and len(layout) > 0:
        candidate = layout[0].get("image_path", "").lstrip("/")
        if os.path.exists(candidate):
            first_panel_img = candidate

    if first_panel_img:
        pdf.ln(10)
        img_x = (210 - 140) / 2
        pdf.image(first_panel_img, x=img_x, y=pdf.get_y(), w=140, h=93)
        pdf.set_xy(20, pdf.get_y() + 98)
    else:
        pdf.ln(50)

    # Metadata card box
    box_y = 215
    pdf.set_xy(30, box_y)
    pdf.set_fill_color(26, 36, 56)
    pdf.set_draw_color(56, 189, 248)
    pdf.set_line_width(0.5)
    pdf.rect(30, box_y, 150, 48, "DF")

    pdf.set_xy(35, box_y + 6)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(56, 189, 248)
    pdf.cell(140, 6, _clean_text("COMIC ATTRIBUTES:"), align="L", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(241, 245, 249)
    pdf.set_x(35)
    pdf.cell(140, 6, _clean_text(f"Tone: {tone}"), align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(35)
    pdf.cell(140, 6, _clean_text(f"Art Style: {art_style}"), align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(35)
    pdf.cell(140, 6, _clean_text(f"Total Panels: {len(layout)} Sequential Acts"), align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(35)
    pdf.cell(140, 6, _clean_text("Generated by Google Gemini AI & Stable Diffusion"), align="L", new_x="LMARGIN", new_y="NEXT")

    # ----------------------------------------------------
    # PANEL PAGES (One panel per page for clean read)
    # ----------------------------------------------------
    for panel in layout:
        pdf.add_page()
        p_num = panel.get("panel", 1)
        p_title = panel.get("title", f"Panel {p_num}")
        p_desc = panel.get("description", "")
        p_caption = panel.get("caption", "")
        p_narration = panel.get("narration", "")
        p_dialogue = panel.get("dialogue", "")
        img_rel = panel.get("image_path", "").lstrip("/")

        # Top border line
        pdf.set_draw_color(255, 87, 34)
        pdf.set_line_width(1.5)
        pdf.line(15, 12, 195, 12)

        # Panel Banner Header
        pdf.set_xy(15, 16)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(180, 8, _clean_text(f"PANEL {p_num}: {p_title.upper()}"), align="L", new_x="LMARGIN", new_y="NEXT")

        # Scene description (italic setting)
        if p_desc:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 116, 139)
            pdf.multi_cell(180, 5, _clean_text(f"Scene: {p_desc}"))
            pdf.ln(3)

        # Illustration
        if img_rel and os.path.exists(img_rel):
            curr_y = pdf.get_y()
            img_w = 175
            img_h = 116
            pdf.image(img_rel, x=17.5, y=curr_y, w=img_w, h=img_h)
            pdf.set_draw_color(30, 41, 59)
            pdf.set_line_width(0.8)
            pdf.rect(17.5, curr_y, img_w, img_h)
            pdf.set_xy(15, curr_y + img_h + 6)
        else:
            pdf.ln(8)

        # Ambient Caption Box
        if p_caption:
            pdf.set_fill_color(241, 245, 249)
            pdf.set_draw_color(203, 213, 225)
            pdf.set_line_width(0.3)
            cap_y = pdf.get_y()
            pdf.rect(15, cap_y, 180, 8, "DF")
            pdf.set_xy(18, cap_y + 1)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(255, 87, 34)
            pdf.cell(174, 6, _clean_text(f">> {p_caption.upper()}"), align="L", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(4)

        # Narration Box
        if p_narration:
            pdf.set_fill_color(254, 252, 232)
            pdf.set_draw_color(234, 179, 8)
            pdf.set_line_width(0.4)
            narr_start_y = pdf.get_y()
            pdf.set_xy(15, narr_start_y)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(15, 23, 42)
            pdf.multi_cell(180, 5.5, _clean_text(p_narration), border=1, fill=True)
            pdf.ln(4)

        # Dialogue Balloon Box
        if p_dialogue:
            pdf.set_fill_color(240, 249, 255)
            pdf.set_draw_color(56, 189, 248)
            pdf.set_line_width(0.6)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(3, 105, 161)
            pdf.multi_cell(180, 6, _clean_text(f"[Speech]: {p_dialogue}"), border=1, fill=True)
            pdf.ln(4)

        # Footer page indicator
        pdf.set_xy(15, 282)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(180, 6, _clean_text(f"ComicCraft AI Studios  |  Panel {p_num} of {len(layout)}"), align="R")

    pdf.output(output_path)
    logger.info("Generated PDF comic successfully at %s", output_path)
    return f"/static/exports/{filename}"
